# Generated by Django 3.0.8 on 2020-07-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200723_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='chat',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='chat.Chat'),
        ),
    ]
