# Generated by Django 3.0.8 on 2020-07-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='user_photo')),
                ('image2', models.ImageField(blank=True, upload_to='user_photo')),
                ('image3', models.ImageField(blank=True, upload_to='user_photo')),
                ('image4', models.ImageField(blank=True, upload_to='user_photo')),
                ('image5', models.ImageField(blank=True, upload_to='user_photo')),
                ('image6', models.ImageField(blank=True, upload_to='user_photo')),
                ('image7', models.ImageField(blank=True, upload_to='user_photo')),
                ('image8', models.ImageField(blank=True, upload_to='user_photo')),
                ('image9', models.ImageField(blank=True, upload_to='user_photo')),
                ('image10', models.ImageField(blank=True, upload_to='user_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
