# Generated by Django 3.0.8 on 2020-07-07 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermedia',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='image9',
        ),
        migrations.AddField(
            model_name='usermedia',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
