# Generated by Django 3.0.8 on 2020-07-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0002_auto_20200707_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='title',
        ),
    ]
