# Generated by Django 3.0.8 on 2020-07-08 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_media', '0003_remove_usermedia_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
