# Generated by Django 3.0.8 on 2020-07-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0004_auto_20200708_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermedia',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image2',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image3',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image4',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image5',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image6',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image7',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image8',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='image9',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
    ]
