# Generated by Django 3.0.8 on 2020-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='person',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
